snakemake/snakemake-wrappers

bio/bcftools/norm/environment.yaml, bio/bcftools/norm/meta.yaml, bio/bcftools/norm/test/Snakefile, bio/bcftools/norm/wrapper.py
Simply copied structure from existing bcftools-view. For future development, it might be nice to auto-detect the output format from 'output' and set the `-O` parameter accordingly.
=> Added bcftools-norm wrapper

bio/reference/ensembl-variation/wrapper.py
Apparently ensemble changed filename chr suffix from _ to -
e.g.
ftp://ftp.ensembl.org/pub/release-98/variation/vcf/homo_sapiens/homo_sapiens_chr1.vcf.gz
to
ftp://ftp.ensembl.org/pub/release-98/variation/vcf/homo_sapiens/homo_sapiens-chr1.vcf.gz
=> changed ensemble _ to -

bio/gatk/baserecalibrator/environment.yaml
GATK baserecalibrator runs into a nullpointer-exception for java = 11. It is recommended to run GATK on java = 8
=> GTAK baserecalibrator dependency openjdk=8

bio/snpeff/wrapper.py
This PR fixes an error where snpeff fails with the following input error: `Error:  Cannot read input file '/dev/fd/63'`.
This is resolved by adding a directed-pipe.
=> Modified snpeff call

bio/sra-tools/fasterq-dump/environment.yaml, bio/sra-tools/fasterq-dump/meta.yaml, bio/sra-tools/fasterq-dump/test/Snakefile, bio/sra-tools/fasterq-dump/wrapper.py
This PR:
1. Adds a `sra-tools` minimum version to guarantee `fasterq-dump` is included in the bioconda install.
2. Adds `--threads` to `fasterq-dump`
=> Add min version and threads for fasterq-dump

bio/freebayes/environment.yaml, bio/freebayes/test/Snakefile_bed, bio/freebayes/wrapper.py
As the current freebayes wrapper builds a not-so-nice sed command this PR aims for refactoring.
The main difficulty is not parsing the command by python but to replace the regex by a valid one being correctly interpreted by sed.
The current sed comment for replacing colons and hyphens by tabs looks as following (without separating the chromosome name):
`sed "s/:\([0-9]*\)-\([0-9]*\)$/$(printf '\t')\1$(printf '\t')\2/g"`
For testing I propose the minimal example:
`echo "MT0:1-AB:10-100" | sed "s/:\([0-9]*\)-\([0-9]*\)$/$(printf '\t')\1$(printf '\t')\2/g"`
The result should be `MT0:1-AB	10	100`
=> Refinement of sed call for freebayes

bio/reference/ensembl-variation/test/Snakefile, bio/reference/ensembl-variation/wrapper.py
Apartently both b(g)zip format as well as tabix indices in ensembl archives can be problematic, at least with older releases. These changes try to work around the issues, by explicitly downloading and recompressing vcf files.
=> Fix variation download wrapper

bio/freebayes/test/Snakefile
In my local pipeline, with BAMs covering only one chromosome, freebayes failed to recompute indexes on the fly. So it seems like the BAI files should be required input alongside the BAM files. As these are easily and quickly generated with another wrapper and aren't very big, it is in any case cleaner to have them generated once and then lying around next to the BAMs---this way, whenever they are needed with an index again (e.g. delly), it's there.
=> include BAM indexes BAI as freebayes required input

bio/delly/wrapper.py
Previously, the keyword `exclude` must not be part of the input if no region should be excluded.
Now the keyword can existing, containing an empty string in which case still no region gets excluded.
=> Improved exclusion handling

bio/gdc-api/bam-slicing/wrapper.py
With not being able to use a genuine token, the test didn't catch this -- the token has to pasted verbatim into the API request being made.
But as far as I can see, this does not pose the risk of exposing the token via snakemake logs, as the exact command being run is hidden behind the temporary `wrapper.py` in the `.snakemake/log` files. But @johanneskoester, if you see any possibility of the token being put somewhere where users might (accidentally) make it publicly available, please do say! We definitely don't want this as a side-effect, also not in any future versions of snakemake (e.g. if there are any plans of putting the temporary wrapper.py contents in the log eventually).
=> fix gdc api token reading

bio/ptrimmer/environment.yaml, bio/ptrimmer/wrapper.py
This updates the wrapper to pTrimmer 1.3.2.
As the latest version of pTrimmer has replaced the output-folder argument by output file arguments these have been replaced.
Moreover pTrimmer now automatically identifies if the output files contain a gz-extension so creating an archive not required anymore.
Nevertheless, pTrimmer can not handle file-paths for output files. Which is why the wrapper must strip the filename from the output and move the resulting files to the final output directory.
=> Updated wrapper for pTrimmer v1.3.2

bio/multiqc/environment.yaml
Latest MultiQC release is 1.9 (https://github.com/ewels/MultiQC/releases) it includes new features and bug fixes in existing modules, especially proper handling of fastqc reports for empty bam files.
=> MultiQC updated to 1.9

bio/deepvariant/environment.yaml, test.py
DeepVariant's bioconda package installs tensorflow-estimator dependently, but the DeepVariant wrapper now fails to import tensorflow because "the conda-forge tensorflow-estimator" was updated a few days ago. I had to explicitly specify a version of tensorflow-estimator to solve this.
=> DeepVariant fixed

bio/optitype/test/Snakefile, bio/optitype/wrapper.py, test.py
Fix for OptiType wrapper to infer the output dir from the path of the output files.
=> Optitype - generalized output directory

bio/fastqc/wrapper.py
Quote input and output files to ensure the wrapper works when used with
files that contain spaces in the name
=> Quote input/output files in fastqc wrapper

bio/picard/collectmultiplemetrics/meta.yaml, bio/picard/collectmultiplemetrics/wrapper.py
@dlaehnemann : An update for picard's CollectMultipleMetrics wrapper. As you suggested the extensions were created as dict in the wrapper and now match to the full extension at the end of a path. The table for assigning tools to their extensions moved to description in meta.yaml file and has received some design changes.
=> Update for Wrapper Picard CollectMultipleMetrics

bio/strelka/somatic/wrapper.py
See title. Wrapper looked for "normalBam" in `snakemake.input.keys()`, but the key is called "normal".
=> Fix normal bam accession in wrapper

bio/bcftools/mpileup/environment.yaml, bio/bcftools/mpileup/meta.yaml, bio/bcftools/mpileup/test/Snakefile, bio/bcftools/mpileup/test/genome.fasta, bio/bcftools/mpileup/test/genome.fasta.fai, bio/bcftools/mpileup/test/mapped, bio/bcftools/mpileup/wrapper.py, test.py
In addition to adding this wrapper, I would also like to suggest changing the `bcftools call` wrapper to stop using `samtools mpileup` (which is deprecated) and instead only make that wrapper run `bcftools call`. I know the bcftools docs give the example of piping the output of `mpileup` into `call`, but `mpileup` can take a long time to run so I prefer having it run separately so I have that intermediate file on hand in case `call` needs to be rerun. If others don't want to keep that `mpileup` file lying around they can just tag it with [`temp()`](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#protected-and-temporary-files) obviously.
=> add bcftools mpileup wrapper

bio/ucsc/bedGraphToBigWig/test/Snakefile, bio/ucsc/faToTwoBit/test/Snakefile, bio/ucsc/twoBitInfo/test/Snakefile, bio/ucsc/twoBitToFa/test/Snakefile
The ucsc wrappers already handle logging output, but the example `Snakefile`s did not contain a `log:` entry. This PR adds this.
=> Add log to ucsc examples

docs/index.rst
Just fixing the link in the docs. I assume the default behaviour is to pull from GitHub now?
=> Replacing Bitbucket with GitHub link

bio/optitype/environment.yaml
Until version 1.3.4, OptiType writes temporary BAM files and names them after the current date and time. In combination with a workflow engine that potentially spawns multiple optitype instances within one second, this causes name collisions.
This was fixed in 1.3.5, the temporary BAM file names now take `--prefix` into account.
=> Bump OptiType version to 1.3.5

bio/picard/markduplicates/wrapper.py, docs/generate_docs.py
Hi,
I was wondering if this is a good idea or not: based on the `resources` parameter in snakemake rules, then build `-Xmx` parameter automatically for any java tool that allow this kind of parameters.
Here, the conda wrapper of almost any picard subcommands handles `-Xm*`, and `-D*` options, so `Xmx` is handled.
If you agree with this, I am willing to do the same in Picard, SnpSift, SnpEff, GATK and Trinity (max_memory). If you see any other tool that would need such changes, please tell me and I'll be happy to make the changes.
Thanks in advance for your reviews.
PS: The modifications in `generate_docs.py` come from a PR i did this morning. I don't know how to hide it since it has been already accepted.
=> Java (picard) -Xmx parameter

bio/macs2/callpeak/meta.yaml, bio/macs2/callpeak/test/Snakefile, bio/macs2/callpeak/wrapper.py
Update for macs2 callpeak wrapper in case the --broad-cutoff value is set but the --broad option is missing in params.
=> update for macs2 callpeak wrapper for --broad option

docs/index.rst
Small correction to add the sphinx-copybutton package to build the docs without errors. It fixes #208 
Thanks in advance for the reviews,
=> Explicitly add sphinx-copybutton dependency (fixes #208)

bio/seqtk/subsample/pe/environment.yaml, bio/seqtk/subsample/se/environment.yaml
The `seqtk/subsample` wrapper didn't work for me because I didn't have pigz installed in my environment. This PR updates the corresponding env files to make sure this doesn't happen.
=> Ensure pigz dependency is installed

docs/generate_docs.py
Simple fix for the warning when building the documentation. According to the [pyyaml docs]( https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) it is also safer.
Best, 
Charlie
=> Specify the YAML loader (fixes #239)

bio/cutadapt/pe/test/Snakefile, bio/cutadapt/pe/wrapper.py, bio/cutadapt/se/test/Snakefile, bio/cutadapt/se/wrapper.py, bio/fastp/test/Snakefile, bio/fastp/wrapper.py
Some wrappers have `params.extra`, `params.others`, `params.adapters`, or just `params`.
I think it would be nice to have it a bit more consistent across different wrappers, and having `adapters` on a separate `params`  makes it a little easier sometimes (since adapter specification can differ quite a bit between tools).
=> Added params extra and adapters for consistentency

bio/dada2/add-species/meta.yaml, bio/dada2/add-species/test/Snakefile, bio/dada2/assign-taxonomy/meta.yaml, bio/dada2/assign-taxonomy/test/Snakefile, bio/dada2/dereplicate-fastq/meta.yaml, bio/dada2/filter-trim/meta.yaml, bio/dada2/filter-trim/test/Snakefile, bio/dada2/learn-errors/meta.yaml, bio/dada2/learn-errors/test/Snakefile, bio/dada2/learn-errors/wrapper.R, bio/dada2/make-table/meta.yaml, bio/dada2/make-table/test/Snakefile, bio/dada2/merge-pairs/meta.yaml, bio/dada2/merge-pairs/test/Snakefile, bio/dada2/quality-profile/meta.yaml, bio/dada2/remove-chimeras/meta.yaml, bio/dada2/remove-chimeras/test/Snakefile, bio/dada2/sample-inference/meta.yaml, bio/dada2/sample-inference/test/Snakefile, test.py
Hi,
Here are a final PR to clean up the recently added `dada2` wrappers (thanks to @dlaehnemann).
* Add links to tutorial sections
* Fix typos
* Format nicely function names for the docs
* Reorder the test in `test.py`
* Wrap lines for dada2 tests.
The `make html` for the docs ran smoothly.
If you spot something else, do not hesitate!
Best, 
Charlie
=> Cleaning dada2 wrappers

bio/gatk3/indelrealigner/meta.yaml, bio/gatk3/indelrealigner/test/Snakefile, bio/gatk3/indelrealigner/wrapper.py, bio/gatk3/realignertargetcreator/meta.yaml, bio/gatk3/realignertargetcreator/test/Snakefile, bio/gatk3/realignertargetcreator/wrapper.py
Added automated detection of BAI file (generated by default), memory, and temp dir.
Set BED file as an input file and not a parameter.
=> Automated detection of BAI file, memory, and temp dir

bio/mapdamage2/environment.yaml
=> Add missing R dependencies

bio/cutadapt/se/wrapper.py
Before: "paired-end"
After: "single-end"
=> Fix a typo in docstring.

bio/gatk/variantrecalibrator/wrapper.py
As stated in the subject; I can't get the live version to run without error.  https://gatk.broadinstitute.org/hc/en-us/articles/360037594511-VariantRecalibrator shows the proper syntax.
=> Fixed a couple of typos inputting resource files to gatk VariantRecalibrator.

bio/busco/environment.yaml, bio/busco/wrapper.py
As of version 4.0.0 on onwards, the command to run busco is no longer run_busco as it used to be, and is now simply 'busco'. This breaks the wrapper. I have edited it to the correct 'busco'
=> update run_busco command to busco

bio/picard/markduplicates/meta.yaml, bio/picard/markduplicates/test/Snakefile, bio/picard/markduplicates/wrapper.py
As noted in https://gatk.broadinstitute.org/hc/en-us/articles/360035889471-How-should-I-pre-process-data-from-multiplexed-sequencing-and-multi-library-designs- :
> 2. Merge read groups and mark duplicates per sample (aggregation + dedup)
> 
> Once you have pre-processed each read group individually, you merge read groups belonging to the same sample into a single BAM file. You can do this as a standalone step, bur for the sake of efficiency we combine this with the per-sample duplicate marking step (it's simply a matter of passing the multiple inputs to MarkDuplicates in a single command).
=> Implemented running MarkDuplicates on multiple bams.

bio/deepvariant/environment.yaml, bio/deepvariant/meta.yaml, bio/deepvariant/test/Snakefile, bio/deepvariant/wrapper.py, test.py
This PR updates the deepvariant wrapper to v1.0.0. Since the bioconda deepvariant recipe now supports GPU acceleration this means performance improvements both with regards to variant calling performance and runtime. 
The PR also adds support for generating gVCFs, includes a test for this, and resolves a bug in how the `basename` variable is computed.
=> Deepvariant 1.0

bio/bwa/mem/environment.yaml, bio/bwa/mem/test/Snakefile_samtools, bio/bwa/mem/wrapper.py, test.py
Hey! The bwa mem wrapper is using samtools 1.9 currently. The latest version is 1.12, and it provides the nifty `--write-index` flag. I've added an optional parameter to add this flag in the wrapper, as well as a test to see that this works. Solved this by letting the param take the value `True` to add the flag - not sure if this is the best way to do it, but it seems to work.
=> Updates bwa-mem samtools to v1.12, adds `--write-index` flag

bio/multiqc/environment.yaml
Updata multiqc version to 1.10.1
multiqc 1.9 could not parse *.zip file, which is the result of fastqc.
=> Updata multiqc version to 1.10.1

bio/bismark/bam2nuc/environment.yaml, bio/bismark/bismark/environment.yaml, bio/bismark/bismark2bedGraph/environment.yaml, bio/bismark/bismark2report/environment.yaml, bio/bismark/bismark2summary/environment.yaml, bio/bismark/bismark_genome_preparation/environment.yaml, bio/bismark/bismark_methylation_extractor/environment.yaml, bio/bismark/deduplicate_bismark/environment.yaml
Updates bismark related wrappers environment.yaml to bismark ==0.23.0  and bowtie2==2.4.2. 
I was getting a libtbb file not found error during the bowtie2-build-s stage in the bismark_genome_preparation step.
=> Updates bismark related wrappers environment.yaml to bismark ==0.23.0  and bowtie2==2.4.2

bio/deepvariant/environment.yaml, bio/deepvariant/test/Snakefile, bio/deepvariant/wrapper.py
This PR updates DeepVariant to v1.1.0. The upstream bioconda recipe does not yet support e.g. DeepTrio, but the PR https://github.com/bioconda/bioconda-recipes/pull/27988 adds the missing `--sample_name` argument to the `dv_make_examples.py` wrapper. This in turn avoids problems downstream, as samples in vcfs may have other names than `default`.
=> Updates deepvariant to v1.1.0

bio/sambamba/view/wrapper.py
Avoid redirecting stdout to the log since sambamba view output is via
stdout
=> Fix sambamba view wrapper output

bio/cutadapt/pe/wrapper.py
The current version raises an exception when in line 20, neither extra nor adapters is specified.  Based on this logic, it should be the case that if either is specified the command should work, but if params.adapters is not specified, the shell command fails (because params.adapters does not exist in line 25).
=> Update wrapper.py for cutadapt/pe.

bio/bcftools/concat/environment.yaml, bio/bcftools/concat/meta.yaml, bio/bcftools/concat/test/Snakefile, bio/bcftools/concat/wrapper.py
These options are quite common across `bcftools` tools (and there might be others, like `tmp_dir` or `max_mem`) so, it might make sense to have them parsed on `snakemake_wrapper_utils`, just like it is currently done for `java`. The same could be done for `samtools`, (e.g.):
- `snakemake_wrapper_utils.bcftools`
- `snakemake_wrapper_utils.samtools`
=> Automatically detect threads and output format on bcftools

bio/trinity/wrapper.py
Trinity outputs on stdout; this should be sent to the log file as well.
=> Trinity output on stdout to log

bio/trim_galore/pe/environment.yaml, bio/trim_galore/pe/test/Snakefile, bio/trim_galore/se/environment.yaml, bio/trim_galore/se/test/Snakefile
* [ x] there is a test case which covers any introduced changes,
* [ x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [ x] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [ x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [ x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [ x] all fields of the example rules in the `Snakefile`s and their entries are explained via …
=> Bump trim_galore version and fix formatting

bio/picard/markduplicates/test/Snakefile
The wrapper uses named parameter 'extra' to get value from params but it is missing in the testing snakefile
=> add 'extra' in testing snakemake file

bio/cutadapt/se/wrapper.py
Line 20 (and practical use of cutadapt) suggests, that defining only adapters or extra in params should work. However currently omitting either results in AttributeError.
Proposed change allows for defining only adapters or only extra, which much better suits practical use of cutadapt.
=> Cutadapt/se: fixed bug in wrapper.py

bio/bowtie2/align/environment.yaml, bio/bowtie2/build/environment.yaml
I updated the bowtie version used in the environment.yml file from bowtie2 v2.4.1 to bowtie2 v2.2.4
I updated the environment.yml files for both bowtie align and bowtie build so that the versions match
I did not change anything else except for the bowtie2 version in both environment.yml files, so I have not ticked any boxes below as this is a very minor fix.
=> Changed bowtie2 version for wrapper to avoid dyld: Library not loaded: @rpath/libtbb.dylib error

bio/reference/ensembl-variation/test/Snakefile, bio/reference/ensembl-variation/test/chrom_wise.smk, bio/reference/ensembl-variation/wrapper.py, test.py
Allow to define a chromosome when downloading ensembl variation.
=> feat: Chromosome wise ensembl variation download

bio/strelka/germline/wrapper.py
This PR adds parentheses around the body of the strelka germline shell script to catch the log information of both parts in the logfile, fixing a previous error.
=> Added parentheses to include both steps in log

bio/rasusa/environment.yaml, bio/rasusa/meta.yaml, bio/rasusa/test/Snakefile, bio/rasusa/wrapper.py, docs/_templates/wrapper.rst, docs/contributing.rst
Updated the `rasusa` wrapper to version 0.6.
I also added a directive in the wrapper docs template to allow explicit newlines in the `meta.yaml` fields with the use of `|nl|`.
=> update rasusa to v0.6

bio/vep/annotate/wrapper.py
Currently, filenames with whitespaces are not supported letting the wrapper fail. As some tools create vcf and bcf-files containing whitespaces quotes have been added for input in order to be correctly read by bcftools.
=> Update VEP annotate: Allows whitespaces in file names

.github/workflows/main.yml, bio/freebayes/environment.yaml, bio/freebayes/meta.yaml, bio/freebayes/test/Snakefile, bio/freebayes/wrapper.py
When setting `normalize = True` die rule fails as `bcftools norm` requires a parameter.
This is fixed by changing the `normalize` parameter into a string allowing the user to select the desired parameter. 
=> Fix freebayes normalization

bio/gatk/genomicsdbimport/environment.yaml, bio/gatk/genomicsdbimport/meta.yaml, bio/gatk/genotypegvcfs/environment.yaml, bio/gatk/genotypegvcfs/meta.yaml, bio/gatk/genotypegvcfs/test/Snakefile, bio/gatk/haplotypecaller/environment.yaml, bio/gatk/haplotypecaller/meta.yaml, bio/gatk/haplotypecaller/test/Snakefile
=> GATK version update

bio/star/align/wrapper.py
This change allows a user to use output prefixes that are not limited to an output directory, but could also include other information.
This is useful in cases when one would like for the output sam/bam files to include for example the sample name in the file name itself (useful when loading multiple bam files into visualisers).
=> Make STAR output prefix more flexible

bio/fgbio/annotatebamwithumis/environment.yaml, bio/fgbio/annotatebamwithumis/test/Snakefile, bio/fgbio/annotatebamwithumis/wrapper.py
As `fgbio AnnotateBamWithUmis` is very memory consuming and tends to fail with an OutOfMemory-Error an optional `java_opts`-parameter has been added.
Also fgbio has been updated to its latest release.
=> Add java_opts

bio/vep/annotate/meta.yaml, bio/vep/annotate/test/Snakefile, bio/vep/annotate/wrapper.py
As plugins may require aux-files these are now read from the input.
In case of aux files that are placed in the cache-directory by default the wrapper automatically adds these to the parameter string. 
In case no input with the plugin name exists or no default file is in the cache directory the wrapper assumes that no aux-file is required to apply the plugin.
=> Enhance vep annotate

bio/gatk/haplotypecaller/test/Snakefile, bio/gatk/haplotypecaller/wrapper.py
Added support for automated thread specification.
=> Added support for automated thread specification

bio/star/align/environment.yaml, bio/star/align/meta.yaml, bio/star/align/test/Snakefile, bio/star/align/wrapper.py
=> fix: proper tempfile handling for STAR and improved documentation

bio/vardict/wrapper.py
fix: add missing extra to shell
=> fix: fix passing of extra args in vardict wrapper

bio/multiqc/environment.yaml
Update multiqc version to v1.11.
multiqc v1.10.1 used `collections.Mapping` here https://github.com/ewels/MultiQC/blob/v1.10.1/multiqc/utils/config.py#L256.
This is deprecated with Python 3.10 and updated to `collections.abc.Mapping` in multiqc v1.11 (https://github.com/ewels/MultiQC/blob/v1.11/multiqc/utils/config.py#L270).
=> feat: update multiqc wrapper to v1.11

bio/samtools/fastq/separate/environment.yaml, bio/samtools/fastq/separate/wrapper.py
Use new `get_mem` function to provide `samtools sort` with memory per-thread.
=> feat: parse mem for samtools sort

bio/subread/featurecounts/meta.yaml, bio/subread/featurecounts/test/Snakefile, bio/subread/featurecounts/wrapper.py
=> feat: added temp dir to featurecounts

bio/star/align/environment.yaml, bio/star/align/meta.yaml, bio/star/align/test/Snakefile, bio/star/align/wrapper.py, bio/star/index/environment.yaml, bio/star/index/meta.yaml, bio/star/index/test/Snakefile, bio/star/index/wrapper.py, meta/bio/star_arriba/test/Snakefile, test.py
Add a temp dir and made output file names more flexible. Now, all of STAR output is saved to a temp dir and only those files specified as outputs by the user are copied over to the final location
=> feat: added STAR temp dir

bio/bwa/aln/test/Snakefile, bio/bwa/mem-samblaster/test/Snakefile, bio/bwa/mem/test/Snakefile, bio/bwa/mem/test/Snakefile_picard, bio/bwa/mem/test/Snakefile_samtools, bio/bwa/sampe/test/Snakefile, bio/bwa/sampe/test/Snakefile_picard, bio/bwa/sampe/test/Snakefile_samtools, bio/bwa/samse/test/Snakefile, bio/bwa/samse/test/Snakefile_picard, bio/bwa/samse/test/Snakefile_samtools, bio/bwa/samxe/meta.yaml, bio/bwa/samxe/test/Snakefile, bio/bwa/samxe/test/Snakefile_picard, bio/bwa/samxe/test/Snakefile_samtools, bio/bwa/samxe/wrapper.py
Following #232, doing the same for the `smaxe` wrapper. 
=> feat: explicitly specify bwa index in bwa samxe

bio/biobambam2/bamsormadup/wrapper.py, bio/gatk/applybqsrspark/wrapper.py, bio/multiqc/environment.yaml
Hi,
I've been having constant problems with this wrapper. My Snakemake execution almost always hangs in the "Solving environment step". I was supportive of merging #422 but considering MultiQC is on version 1.12, I believe it would be better to drop this pinned version. I tried creating the environment from the file as it is in this PR and it correctly installs v1.12 of MultiQC.
Ping @fgvieira @thomasbtf, would you agree?
Thank you for any assistance you can provide.
Cheers,
Vini
Summary of changes:
- Remove '= 1.11' from multiqc environment yaml
MultiQC has been updated to 1.12 and pinning v1.11 is hampering environment solving.
@thomasbtf @fgvieira would you be okay with this?
=> fix: update multiqc version to 1.12

bio/gatk/mutect/wrapper.py
The genotype likelihood calculation [by default uses 4 threads](https://gatk.broadinstitute.org/hc/en-us/articles/360046788432-Mutect2#--native-pair-hmm-threads), and the threads parameter was never passed on to Mutect2. This pull request addresses this issue.
=> fix: have mutect2 respect snakemake threads

bio/bcftools/filter/wrapper.py
=> fix: bcftools filter cannot run with mem options and this will prevent mem-max to be set.

bio/picard/collectmultiplemetrics/meta.yaml, bio/picard/collectmultiplemetrics/wrapper.py
=> fix: issue 339

utils/nextflow/environment.yaml, utils/nextflow/wrapper.py
- Fixed bug where Nextflow *-profile* option was inserted also second time with double hyphens (--profile ..) to nextflow call. 
- Added snakemake *extra* parameter to pass other single hyphen options to nextflow (e.g. -resume []).
- Removed nextflow version from environment file.
All these have been tested by running nf-core/mag pipeline.
=> fix: Nextflow profile

bio/bowtie2/align/environment.yaml, bio/bowtie2/align/meta.yaml, bio/bowtie2/align/test/Snakefile, bio/bowtie2/align/wrapper.py, bio/bowtie2/build/environment.yaml, bio/bowtie2/build/meta.yaml, bio/bowtie2/build/test/Snakefile, bio/bowtie2/build/wrapper.py, test.py
Fixed several issues (#277, #355, #457, and maybe #372), added docs, and reformat.
=> fix: fixed some known bugs, added docs, and reformat

bio/gatk/splitncigarreads/wrapper.py, bio/samtools/fastq/separate/wrapper.py
Fixed an issue when several output files are specified (e.g. BAI).
=> fix: fixed issue when several output files are specified with gatk splitncigarreads wrapper

.github/workflows/main.yml, .github/workflows/qc.yml
=> chore: fix mamba setup

bio/subread/featurecounts/meta.yaml, bio/subread/featurecounts/test/Snakefile, bio/subread/featurecounts/wrapper.py
Added `param` option to specify strandness (like in picard collectrnametrics)
=> feat: Added specific param for strandness

bio/picard/collectrnaseqmetrics/meta.yaml, bio/picard/collectrnaseqmetrics/test/Snakefile, bio/picard/collectrnaseqmetrics/wrapper.py
=> feat: added ref as an optional input file

bio/bwa-mem2/mem/environment.yaml, bio/bwa/mem/environment.yaml, bio/bwa/sampe/environment.yaml, bio/bwa/samse/environment.yaml, bio/bwa/samxe/environment.yaml
Previously, the bwa wrappers pulled in the full `picard` bioconda package, which includes extensive extra dependencies that are not necessary for the functionality of the wrapper. `picard-slim` instead excludes as many extra dependencies, such as `r-base`.
=> fix: restrict bwa wrappers' picard installation to picard-slim (e.g. removes r-base dependency)

bio/multiqc/meta.yaml, bio/multiqc/test/Snakefile, bio/multiqc/wrapper.py, test.py
make it possible to use the actual input from the rule as input to multiqc, instead of converting it to dirs that are then searched.
If multiqc search directories it's possible that unwanted files are included to the reports. This will make it possible to only use the provided files, when wanted.
=> feat: make it possible to set input as files or dirs to multiqc

.github/workflows/main.yml
=> fix: use strict channel priorities

bio/kallisto/index/test/Snakefile, bio/kallisto/quant/test/Snakefile
=> fix: remove misleading kmer size parameter for kallisto index

bio/reference/ensembl-sequence/wrapper.py
=> fix: better error handling for ensembl sequence download

bio/cutadapt/pe/environment.yaml, bio/cutadapt/pe/meta.yaml, bio/cutadapt/pe/test/Snakefile, bio/cutadapt/pe/wrapper.py, bio/cutadapt/se/environment.yaml, bio/cutadapt/se/meta.yaml, bio/cutadapt/se/test/Snakefile, bio/cutadapt/se/wrapper.py
Updated cutadapt version to v4, formated files with `black` and `snakefmt`, and improved docs.
=> perf: updated cutadapt version, formated files, and improved docs.

bio/star/align/meta.yaml, bio/star/align/test/Snakefile, bio/star/align/wrapper.py, meta/bio/star_arriba/test/Snakefile, test.py
- Allow fastq files compressed with `bz2`
- Fix issue #495 
- Use `stdout` for alignment output, to avoid excessive I/O
=> feat: output aln is saved from stdout, to reduce I/O

bio/minimap2/aligner/environment.yaml, bio/minimap2/aligner/meta.yaml, bio/minimap2/aligner/test/Snakefile, bio/minimap2/aligner/wrapper.py, bio/minimap2/index/environment.yaml, bio/minimap2/index/meta.yaml, test.py
=> feat: fixed minimap2 bioconda strict channels, updated version, and added test

bio/bcftools/norm/environment.yaml
=> perf: update bcftools norm versions

bio/delly/environment.yaml, bio/delly/meta.yaml, bio/delly/test/Snakefile, bio/delly/wrapper.py, test.py
Automated conversion of output `BCF`.
=> feat: delly automated conversion of output file

bio/reference/ensembl-annotation/test/Snakefile, bio/reference/ensembl-annotation/wrapper.py, bio/reference/ensembl-sequence/test/Snakefile, bio/reference/ensembl-sequence/wrapper.py, bio/reference/ensembl-variation/test/Snakefile, bio/reference/ensembl-variation/wrapper.py
=> feat: support branches (e.g. plants) in ensembl wrappers for sequence, annotation, and variation download

bio/vep/annotate/environment.yaml, bio/vep/annotate/wrapper.py, bio/vep/cache/environment.yaml, test.py
=> fix: upgrade vep wrappers to latest version, fixing issues with strict channel priorities.

utils/datavzrd/environment.yaml
=> perf: update to datavzrd wrapper to datavzrd 2.0

bio/bwa-mem2/index/environment.yaml, bio/bwa-mem2/index/meta.yaml, bio/bwa-mem2/index/wrapper.py, bio/bwa-mem2/mem/environment.yaml, bio/bwa-mem2/mem/meta.yaml, bio/bwa-mem2/mem/wrapper.py, bio/bwa/mem/environment.yaml, bio/bwa/mem/meta.yaml, bio/bwa/mem/wrapper.py
Updated versions, added use of tempfile, and use of wrapper utils.
* wherever possible, command line arguments are inferred and set …
=> perf: bwa mem2 version update and use wrapper utils

bio/bcftools/concat/wrapper.py
=> fix: fix regression in bcftools concat wrapper that made it use only the first input file. The bug was introduced in wrapper version v1.8.0.

bio/bcftools/norm/test/Snakefile
=> fix: improve bcftools norm example rule

bio/bismark/bismark_genome_preparation/test/Snakefile
Since the `../wrapper.py` picks up the named params `params_extra = snakemake.params.get("extra", "")`, here is the fix to ensure optional parameters are picked up during execution
=> perf: Update params so wrapper correctly assigns params.extra

bio/gatk/applybqsr/environment.yaml, bio/gatk/applybqsr/test/Snakefile, bio/gatk/applybqsr/test/Snakefile_cram, bio/gatk/applybqsr/wrapper.py, bio/gatk/applybqsrspark/environment.yaml, bio/gatk/applybqsrspark/test/Snakefile, bio/gatk/applybqsrspark/test/Snakefile_cram, bio/gatk/applybqsrspark/wrapper.py, test.py
=> feat: add cram support to applybsqr

.github/workflows/autobump.yml, .github/workflows/main.yml
=> chore: autobump conda envs

utils/datavzrd/environment.yaml
=> perf: update datavzrd wrapper to version 2.5.1

bio/pindel/call/wrapper.py
With the previous implementation the only way of omitting the bed file arguments was if they were completely missing from the rule definition. This change allows for optional bed file arguments, e.g.
```python
rule pindel_call:
input:
include_bed=config.get("include_bed", [])
```
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step …
=> fix: allow for optional pindel bed files

.github/workflows/autobump.yml, docs/_templates/wrapper.rst, docs/generate_docs.py
=> dbg: autobump

bio/bwa-meme/mem/test/Snakefile, bio/bwa-meme/mem/test/hide.smk, bio/bwa-memx/mem/test/Snakefile, bio/bwa-memx/mem/test/hide.smk, test.py
=> fix: bwa-meme and bwa-memx documentation

bio/benchmark/chm-eval-kit/test/Snakefile, bio/benchmark/chm-eval/test/Snakefile, bio/genomepy/test/Snakefile, bio/reference/ensembl-annotation/test/Snakefile, bio/reference/ensembl-sequence/test/Snakefile, bio/reference/ensembl-sequence/test/old_release.smk, bio/reference/ensembl-variation/test/Snakefile, bio/vep/cache/test/Snakefile, meta/bio/star_arriba/test/Snakefile
=> docs: suggest "omit-software" cache behavior for download only wrappers

bio/cooltools/dots/environment.yaml
Latest cooltools requires updated sklearn with the bug fixed
* wherever possible, command line arguments are inferred and set …
=> refactor: remove pinned scikit-learn in cooltools dots

bio/gatk/applybqsr/environment.yaml, bio/gatk/applybqsrspark/environment.yaml, bio/gatk/markduplicatesspark/environment.yaml, bio/gatk/printreadsspark/environment.yaml
=> fix: Removed unnecessary openjdk references

bio/cooltools/insulation/wrapper.py
Recent release of cooltools allows multiple threads in the insulation command, now the wrapper passes the snakemake.threads to the -p argument. …
=> feat: Add threads to cooltools insulation

bio/rsem/calculate-expression/meta.yaml, bio/rsem/calculate-expression/test/Snakefile, bio/rsem/calculate-expression/wrapper.py
The wrapper for **RSEM Calculate Expression** referenced the wrong Snakemake input variables. This was fixed with an additional adding of threads. Also an update of the meta.yaml was performed. …
=> fix: Correct referencing of Snakemake input variables (release: 1.19.2)

bio/samtools/view/meta.yaml, bio/samtools/view/test/Snakefile, bio/samtools/view/wrapper.py
The region to extract with `samtools view` must be specified after the input file (separate from other options), thus a dedicated parameter is required. …
=> feat: samtools view allow region specification

bio/bcftools/filter/environment.yaml, bio/bcftools/filter/wrapper.py
Updated parsing of opts by the wrapper_utils version `0.5.0`.
* wherever possible, command line arguments are inferred and set …
=> fix: updated parsing of bcftools opts

bio/rbt/collapse_reads_to_fragments-bam/wrapper.py
Previously, `params: extra=""` needed to be specified for this wrapper. This PR makes it optional to have `params.extra` specified, providing a default value of empty string (`""`). …
=> fix: make 'params: extra=' optional for rbt collapse_reads_to_fragments-bam wrapper

utils/datavzrd/environment.yaml
=> perf: update datavzrd wrapper to 2.12.0

.github/workflows/main.yml, .github/workflows/qc.yml, test.py
=> fix: snakemake and mamba deployment

bio/rbt/collapse_reads_to_fragments-bam/environment.yaml, bio/rbt/collapse_reads_to_fragments-bam/test/Snakefile, bio/varscan/somatic/environment.yaml, meta/bio/calc_consensus_reads/test/Snakefile
Currently the snakemake meta wrapper does not transfer information defined in the fastq description field to the bam records during remapping the consensus reads.
Thereby strand information are lost in the resulting bam-file.
As a result variants called by varlociraptor do not benefit from these information.
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name …
=> fix: consensus meta wrapper

bio/cooltools/eigs_cis/environment.yaml, bio/cooltools/eigs_trans/environment.yaml, bio/cooltools/expected_cis/environment.yaml, bio/cooltools/expected_trans/environment.yaml, bio/cooltools/genome/binnify/environment.yaml, bio/cooltools/genome/gc/environment.yaml, bio/cooltools/insulation/environment.yaml, bio/cooltools/pileup/environment.yaml, bio/cooltools/saddle/environment.yaml, bio/genefuse/environment.yaml, bio/genomescope/environment.yaml, bio/meryl/sets/environment.yaml, bio/meryl/stats/environment.yaml, bio/qualimap/bamqc/environment.yaml
=> fix: channel definitions for cooltools (and update version to 0.5.2), genefuse, genomescope, qualimap and meryl

utils/datavzrd/environment.yaml
=> perf: update datavzrd to version 2.14.1

bio/vep/cache/wrapper.py
=> fix: properly handle proxy setting in vep cache wrapper

bio/gatk/variantstotable/environment.yaml, bio/gatk/variantstotable/meta.yaml, bio/gatk/variantstotable/test/Snakefile, bio/gatk/variantstotable/test/calls/snvs.vcf, bio/gatk/variantstotable/wrapper.py, test.py
Add GATK VariantsToTable wrapper …
=> feat: Add GATK VariantsToTable

bio/vep/cache/wrapper.py
This should not be necessary, as the fasta can be retrieved with the ensembl reference wrapper
* wherever possible, command line …
=> fix: do not download fasta file in VEP cache wrapper

bio/rsem/calculate-expression/wrapper.py
This pull request addresses the bug mentioned in issue #1074
=> fix: fixed bug in obtaining paired_end parameter for RSEM calculate-expression

bio/bwa-meme/mem/environment.yaml
=> feat: BWA-MEME Version 1.0.6 update

bio/arriba/environment.yaml
Update to v2.4.0
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in …
=> feat: update arriba to 2.4.0

bio/strelka/germline/wrapper.py
=> feat: allowed strelka germline using multiple bam

bio/salmon/quant/environment.yaml
Simple modification of salmon quant environment to install the latest version (v1.10.1)
* wherever possible, command line arguments are …
=> perf: bump Salmon to v1.10.1

utils/datavzrd/environment.yaml
Update datavzrd to latest version …
=> feat: update datavzrd 2.18.1

bio/star/index/meta.yaml, bio/star/index/test/Snakefile, bio/star/index/wrapper.py, meta/bio/star_arriba/test/Snakefile
=> feat: also define overhang on params.extra

utils/datavzrd/environment.yaml
=> perf: update datavzrd to 2.18.5

bio/gatk/modelsegments/environment.yaml, bio/gatk/modelsegments/meta.yaml, bio/gatk/modelsegments/test/Snakefile, bio/gatk/modelsegments/test/a.denoisedCR.tsv, bio/gatk/modelsegments/wrapper.py, test.py
gatk ModelSegments wrapper
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions …
=> feat: gatk modelsegments wrapper

utils/datavzrd/environment.yaml
=> perf: Updated version of datavzrd to 2.19.1

bio/reference/ensembl-annotation/test/Snakefile, bio/reference/ensembl-annotation/wrapper.py
When downloading the annotation fails for GRCh37 releases greater than 87 as the release version in the gft-file remains 87.
This is fixed by adding an extra variable for the release version in the gft filename.
* all `environment.yaml` specifications follow …
=> fix: ensembl annotation GRCh37 gft release

bio/fastqc/environment.yaml, bio/fastqc/meta.yaml, bio/fastqc/test/Snakefile, bio/fastqc/wrapper.py
Added better memory calculation …
=> fix: auto memory calculation

bio/samtools/sort/environment.yaml, bio/samtools/sort/meta.yaml, bio/samtools/sort/wrapper.py, bio/samtools/stats/environment.yaml, bio/samtools/stats/meta.yaml, bio/samtools/stats/test/Snakefile, bio/samtools/stats/wrapper.py
Add memory inference to Samtools Sort …
=> feat: add memory inference to samtools sort

bio/bbtools/bbduk/environment.yaml, bio/bbtools/loglog/environment.yaml, bio/bbtools/tadpole/environment.yaml
Removed unnecessary `python` dependency that, sometimes (at least with the current version), could give errors:
```
Encountered problems while solving:
- package python-3.11.3-h2755cc3_0_cpython requires libzlib >=1.2.13,<1.3.0a0, but none of the providers can be installed
```
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step …
=> fix: removed unnecessary dependencies

bio/snpsift/annotate/wrapper.py
=> fix: fix snpsift annotate output compression (bcf and vcf.gz)

.github/workflows/autobump.yml
`autobump` action should be running every saturday at midnight, but it does not seem to run that often.
GitHub [recommends](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) to "schedule your workflow to run at a different time of the hour".
Not sure if this will help, but it is worth the shot. :smile: 
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about …
=> ci: change cron trigger time to avoid high load times

bio/trim_galore/pe/test/Snakefile, bio/trim_galore/pe/wrapper.py, bio/trim_galore/se/test/Snakefile, bio/trim_galore/se/wrapper.py
Add multiple threads option to trim_galore. 
* wherever possible, command line arguments are inferred and set automatically (e.g. based …
=> fix: add threads to trim_galore

utils/datavzrd/environment.yaml
=> perf: update datavzrd

bio/star/align/meta.yaml, bio/star/align/test/Snakefile, bio/star/align/wrapper.py
Ability to save unmapped reads in fastq or fastq.gz formats using the `--outReadsUnmapped Fastx` option in STAR
* wherever possible, …
=> feat: enable output of unmapped reads

bio/freebayes/environment.yaml
When running freebayes with multiprocessing the execution fails due to an error in `vcflib=1.0.9`(see https://github.com/vcflib/vcflib/issues/389). As a temporary fix vcflib has been added as dependency and pinned to v1.0.3.
To prevent any solving conflicts bcftools needs to be pinned to 1.15.
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., …
=> fix: freebayes wrapper

utils/datavzrd/environment.yaml
=> perf: bump datavzrd to 2.23.1

bio/fgbio/annotatebamwithumis/test/Snakefile, bio/fgbio/annotatebamwithumis/wrapper.py, test.py
Currently, the wrapper tests that `input: umi:` is exactly one file specified as string, but [`fgbio AnnotateBamWithUmis` allows for multiple fastqs specified](https://fulcrumgenomics.github.io/fgbio/tools/latest/AnnotateBamWithUmis.html), which is needed when UMIs are present in multiple reads of the same fragment. Thus, this PR relaxes the testing and tests the scenario with another example rule specifying two fastqs.
* rule names in the test case are in …
=> fix: fgbio annotatebamwithumis allow multiple umi fastq files

utils/datavzrd/environment.yaml
=> perf: bump datavzrd to 2.23.2

utils/datavzrd/environment.yaml
=> perf: bump datavzrd to 2.23.3

utils/datavzrd/environment.yaml
=> perf: bump datavzrd to 2.23.4

test.py, utils/datavzrd/test/Snakefile
There is no test for the datavzrd wrapper which is why the tests are always passing for updates even if the updated version does not exist.  …
=> feat: add test for datavzrd

bio/gatk/genomicsdbimport/test/Snakefile, bio/gatk/genomicsdbimport/wrapper.py
=> feat: Add support for threads to GATK genomicsdbimport

utils/datavzrd/environment.yaml
=> perf: bump datavzrd to 2.23.6

bio/vep/annotate/environment.yaml
=> perf: update vep annotate

bio/picard/markduplicates/environment.yaml
Update snakemake-wrapper-utils as it fixes a bug where `mem_mb` is ignored.
* wherever possible, command line arguments are inferred and …
=> perf: update picard markduplicates

bio/gatk/applyvqsr/environment.yaml, bio/gatk/variantrecalibrator/environment.yaml, bio/picard/sortsam/environment.yaml, bio/snpsift/genesets/environment.yaml
=> perf: update snakemake wrapper utils

utils/datavzrd/environment.yaml
=> perf: update datavzrd 2.23.7

bio/reference/ensembl-variation/wrapper.py
This wrapper is currently failing when concatenating chromosomes.
That issue is caused by each chromosomal vcf having a separate index file only containing the corresponding chromosome itself.
If `csi` files are present `bcftools concat` checks the indexed contigs of each index file and expects them to be present in all of the other vcf headers.
As chromosomes do not overlap it should be fine to drop indexes.
* rule names in the test case are in …
=> fix: ensembl-variation - remove index

utils/datavzrd/environment.yaml
=> perf: update datavzrd 2.23.8

bio/genomepy/meta.yaml, bio/genomepy/test/Snakefile, bio/genomepy/wrapper.py
fixed the genomepy wrapper :partying_face: 
* wherever possible, command line arguments are inferred and set automatically (e.g. based …
=> fix: genomepy wrapper

bio/freebayes/environment.yaml
Freebayes parallel is once again failing due to issues with some of its dependencies. As a workaround htslib need to be pinned to v.1.16 as already described [here](https://github.com/bioconda/bioconda-recipes/issues/42643#issuecomment-1692969153).
* all …
=> fix: fix freebayes parallel

bio/multiqc/environment.yaml, bio/multiqc/meta.yaml, bio/multiqc/test/Snakefile, bio/multiqc/wrapper.py, test.py
=> fix: Fix MultiQC output file issues

bio/multiqc/environment.yaml
Python version is fixed to versions<3.12.0 to handle dependency on imp-module, which is not available in newer python versions. 
The imp module is [deprecated in favor of importlib, and removed from the standard library since python version 3.12.0](https://docs.python.org/3.11/library/imp.html). Thus, depending on the python version your program-call/conda-environment is using, you will encounter a `ModuleNotFoundError` Error.
For further information, see discussion on StackOverflow:  https://stackoverflow.com/questions/77273344/multiqc-snakemake-wrapper-modulenotfounderror-no-module-named-imp
=> fix: Update environment.yaml of MultiQC

test.py
=> ci: add missing @skip_if_not_modified to cnvkit_export

.readthedocs.yaml
=> fix: add readthedocs config file v2

bio/bwa/aln/meta.yaml, bio/bwa/index/meta.yaml, bio/bwa/index/test/Snakefile, bio/bwa/index/wrapper.py, bio/bwa/samxe/meta.yaml, test.py
- Automated infer of block size
- extra tests
- improve docs
- code clean up
* wherever possible, command line arguments are inferred …
=> feat: for bwa, auto infer block size, extra tests, code cleanup and add docs

bio/nonpareil/infer/environment.yaml, bio/nonpareil/infer/meta.yaml, bio/nonpareil/infer/test/Snakefile, bio/nonpareil/infer/wrapper.py
- Auto infer `-X` value
- use `pigz` and `pbzip2`
* wherever possible, command line arguments are inferred and set automatically (e.g. …
=> fix: for nonpareil, use pigz and pbzip2 and auto infer of -X

utils/datavzrd/environment.yaml
=> feat: update datavzrd 2.29.0

utils/datavzrd/environment.linux-64.pin.txt
Adding version pinning for linux as I forget it in the previous PR.
* wherever possible, command line arguments are inferred and set …
=> fix: fix datavzrd version pinning

utils/datavzrd/environment.linux-64.pin.txt, utils/datavzrd/environment.yaml
=> feat: update datavzrd 2.30.0

utils/datavzrd/environment.yaml
=> feat: update datavzrd wrapper to datavzrd `v2.31.0`

bio/multiqc/environment.yaml
Bump version to 1.18, which contains an important fix to recognize sample names from Fastp reports
* wherever possible, command line …
=> fix: Update MultiQC to 1.18

bio/reference/ensembl-sequence/test/Snakefile, bio/reference/ensembl-sequence/wrapper.py, test.py
This will concatenate multiple chromosomes in the order in which they are listed under `params: chromosome:`.
* wherever possible, …
=> feat: allow for specifying multiple chromosomes in ensembl reference dna sequence download wrapper

bio/bcftools/merge/test/Snakefile, bio/bcftools/merge/wrapper.py
Fix for #2295.
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` …
=> fix: issue 2295

bio/bcftools/mpileup/meta.yaml, bio/bcftools/mpileup/test/Snakefile, bio/bcftools/mpileup/wrapper.py
=> fix: add support for multiple samples to bcftools mpileup

utils/datavzrd/environment.yaml
Just a simple update of datavzrd …
=> feat:  datavzrd to 2.33.2

bio/ega/fetch/environment.yaml, bio/ega/fetch/meta.yaml, bio/ega/fetch/test/Snakefile, bio/ega/fetch/wrapper.py, test.py
=> feat: add wrapper for fetching files from EGA

bio/vsearch/environment.linux-64.pin.txt, bio/vsearch/environment.yaml, bio/vsearch/meta.yaml, bio/vsearch/test/Snakefile, bio/vsearch/wrapper.py
Fixed bug with `bz2` output and added the general log too keep console clean and be able to keep track of progress.
* wherever possible, …
=> fix: for vsearch, fixed bug with bz2 output and added general log

bio/reference/ensembl-sequence/test/Snakefile
In the test case rule **_`get_single_chromosome`_** the parameter `chromosome` requires to be an array. Otherwise, if one passes a multi-char string, the wrapper splits the string into its chars and iterates over the chars instead of interpreting the string as a whole.
=> fix: test case for reference-ensembl-sequence wrapper

bio/bbtools/meta.yaml, bio/bbtools/test/Snakefile
The BBmap - generic wrapper appears as only "Generic" Here I renamedit to "BBmap-suite"
BBmap print's everything into stderr, so the effort to split sdout/ stderr is futile.
I adapted the example
* all `environment.yaml` specifications follow [the respective …
=> chore: Name wrapper "BBmap-suite" instead of Generic. 

utils/datavzrd/environment.yaml
=> perf: Update datavzrd to v2.35.4

utils/datavzrd/environment.yaml
=> perf: Update Datavzrd to 2.36.3

utils/datavzrd/environment.yaml
=> perf: Update Datavzrd to 2.36.4

utils/datavzrd/environment.yaml
=> perf: Update Datavzrd to 2.36.8

bio/reference/ensembl-variation/wrapper.py
=> fix: path of .fai file in ensembl-variation wrapper

bio/bwa/mem/environment.linux-64.pin.txt, bio/bwa/mem/environment.yaml, bio/bwa/mem/meta.yaml, bio/bwa/mem/test/Snakefile_fgbio, bio/bwa/mem/wrapper.py, test.py
In some cases sorting reads by `fgbio SortBam` is required as queryname sorting performed by `samtools` results in a different sorting order (see https://github.com/snakemake-workflows/dna-seq-varlociraptor/pull/296). I therefore propose to add `fgbio-minimal` as an addition to the wrapper.  
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., …
=> feat: add fgbio sorting to bwa mem

utils/datavzrd/environment.yaml
=> perf: Update Datavzrd to 2.36.10

utils/datavzrd/test/Snakefile, utils/datavzrd/wrapper.py
=> fix: allow input access in config rendering for datavzrd

bio/deeptools/plotfingerprint/test/Snakefile, bio/deeptools/plotfingerprint/wrapper.py, bio/deeptools/plotheatmap/test/Snakefile, bio/deeptools/plotheatmap/wrapper.py, bio/deeptools/plotprofile/test/Snakefile, bio/deeptools/plotprofile/wrapper.py
Wrapper previously failed if the optional output `qc_metrics` was not supplied due to NA replacement code that was not in a conditional. The code is no longer required since NA strings are now output correctly in https://github.com/deeptools/deepTools/pull/1002 …
=> fix: remove NA string replacement, fixed upstream

bio/deeptools/bamcoverage/test/Snakefile, bio/deeptools/bamcoverage/wrapper.py, test.py
Running deeptools bamcoverage without an effective genome size did not work previously. This PR fixes that issue.
* the …
=> fix: bamcoverage without effective genome size

bio/reference/ensembl-annotation/meta.yaml, bio/reference/ensembl-annotation/test/Snakefile, bio/reference/ensembl-annotation/wrapper.py, bio/reference/ensembl-sequence/meta.yaml, bio/reference/ensembl-sequence/test/Snakefile, bio/reference/ensembl-sequence/wrapper.py, bio/reference/ensembl-variation/meta.yaml, bio/reference/ensembl-variation/test/Snakefile, bio/reference/ensembl-variation/wrapper.py, bio/vep/cache/meta.yaml, bio/vep/cache/test/Snakefile, bio/vep/cache/wrapper.py, test.py
Allow for custom URLs (fix issues #366 and #2649).
* the `environment.yaml` pinning has been updated by running `snakedeploy …
=> fix: issue #366 and #2649

bio/samtools/fastq/separate/test/Snakefile, bio/samtools/fastq/separate/wrapper.py
=> perf: Use samtools collate in fastq separate wrapper

utils/datavzrd/environment.yaml
=> perf: Update Datavzrd wrapper

bio/reference/ensembl-regulation/environment.linux-64.pin.txt, bio/reference/ensembl-regulation/environment.yaml, bio/reference/ensembl-regulation/meta.yaml, bio/reference/ensembl-regulation/test/Snakefile, bio/reference/ensembl-regulation/wrapper.py, test.py
=> feat: add new ensembl-regulation wrapper to systematically download Ensembl regulatory_features

.github/workflows/main.yml
Add `snakemake-storage-plugin-http` plugin to test environment for `aria2c` test (#2725).
* the `environment.yaml` pinning has been …
=> test: add snakemake-storage-plugin-http to test env

bio/cooltools/insulation/wrapper.py
Not sure how it got here and this is deprecated for python 3.13
=> fix: remove unnecessary import

utils/datavzrd/environment.yaml
=> perf: Update Datavvzrd wrapper

bio/arriba/wrapper.py
As the `conda` command is not always available parsing the arriba version might fail.
To circumvent this the version is now read from the help output of arriba using grep. …
=> perf: change version scrapping

bio/reference/ensembl-regulation/wrapper.py
Previously, the wrapper was writing out log infos to the intended output file for compressed (gzipped) output, with the actual output going to a default file name. This was due to a lower case `-o` command line option instead of the correct uppercase `-O` option...
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps …
=> fix: change from wget -o (log file output) to -O (proper output file output)

bio/vep/cache/meta.yaml, bio/vep/cache/test/Snakefile, bio/vep/cache/wrapper.py, test.py
This PR adds a parameter named `indexed` to the wrapper interface to allow downloading a vep_cache version which has already been indexed and thus needs no additional post-processing via `--CONVERT`.
> Tabix-indexed cache files are available to download for most supported species in our [FTP server](https://ftp.ensembl.org/pub/release-112/variation/indexed_vep_cache/). [[1]](http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html)
While the contributions guidelines are more extensive, please particularly ensure that:
=> fix: download already indexed vep cache tarball

bio/trim_galore/pe/wrapper.py
I ran into an error while trying to use the trim_galore/pe wrapper:
```
/path/to/project/.snakemake/scripts/tmph05pgi_u.wrapper.py:38: SyntaxWarning: invalid escape sequence '\.'
REGEX_RULES = [r"\.fastq$", "\.fastq\.gz$", r"\.fq$", r"\.fq\.gz$"]
```
The fix for that issue was easy and obvious, I fixed the raw string for `.fastq.gz` files in the list of regex patterns.
While the contributions guidelines are more extensive, please particularly ensure that:
=> fix: add missing raw string in REGEX_RULES
