bio/freebayes/environment.yaml

Update env for freebayes

---

bio/snpeff/environment.yaml

Updated bcftools for snpeff wrapper

Updated snpeff

---

bio/cutadapt/pe/environment.yaml
bio/cutadapt/se/environment.yaml

Just an update from 2.5 to 2.10 for bugfixes and features.

cutadapt 2.10

---

bio/picard/collecthsmetrics/test/Snakefile

Added missing extra in params.

add extra to params

---

bio/homer/mergePeaks/environment.yaml
bio/homer/mergePeaks/meta.yaml
bio/homer/mergePeaks/test/Snakefile
bio/homer/mergePeaks/test/peaks/a.peaks
bio/homer/mergePeaks/test/peaks/b.peaks
bio/homer/mergePeaks/wrapper.py
test.py

A wrapper for the mergePeaks algorithm from Homer.

Homer-mergePeaks wrapper

---

bio/bcftools/call/environment.yaml
bio/bcftools/call/meta.yaml
bio/bcftools/call/test/Snakefile
bio/bcftools/call/test/a.pileup.bcf
bio/bcftools/call/wrapper.py
test.py

See https://github.com/snakemake/snakemake-wrappers/pull/145#issue-455441639 for reasoning.  
Also, there was no pre-existing test for this wrapper.

update bcftools call wrapper

---

bio/vep/cache/wrapper.py

Added extra to shell in vep cache

---

docs/generate_docs.py

Hi,
This is a fix to the error labelled #187 
It was just a matter of namespace overloading.
Thanks in advance for your reviews

Missing code in wrappers' doc. Error #187

---

bio/dada2/learn-errors/meta.yaml
bio/dada2/learn-errors/test/Snakefile
bio/dada2/learn-errors/wrapper.R

Minor changes to be homogeneous with the others proposed dada2 wrappers. 
Best, 
Charlie

Changes for consistency in dada2 wrapper learnErrors

---

test.py

strategy from PR #240 and issue #239 by @cpauvert

specify yaml loader in test.py

---

bio/dada2/make-table/wrapper.R

ifelse() reduces the length of the vector to 1 instead of keeping the length.
Minor correction to resolves #251

Replace ifelse() by if() (fixes #251)

---

bio/freebayes/test/Snakefile
bio/freebayes/test/Snakefile_bcf
bio/freebayes/test/Snakefile_bed
bio/freebayes/wrapper.py

Sometimes freebayes does not normalize indels. This PR adds an option to activate bcftools norm for this issue,

Add normalization option to freebayes.

---

bio/whatshap/haplotag/environment.yaml
bio/whatshap/haplotag/meta.yaml
bio/whatshap/haplotag/test/Snakefile
bio/whatshap/haplotag/wrapper.py
bio/whatshap/phase/environment.yaml
bio/whatshap/phase/meta.yaml
bio/whatshap/phase/test/Snakefile
bio/whatshap/phase/wrapper.py
bio/whatshap/stats/environment.yaml
bio/whatshap/stats/meta.yaml
bio/whatshap/stats/test/Snakefile
bio/whatshap/stats/wrapper.py

WhatsHap is a tool to provide read-backed phasing of variants.  I have added wrappers for phase, haplotag, and stats subcommands.

added whatshap phase, haplotag, and stats commands

---

bio/fastqc/wrapper.py
bio/freebayes/wrapper.py

Fastqc extensions

---

bio/delly/wrapper.py
bio/mapdamage2/wrapper.py

Fixed some analyses (e.g. model) where the `bam` file is not necessary.

Fixed issue when input file is not required

---

bio/delly/wrapper.py
bio/gatk/haplotypecaller/test/Snakefile
bio/gatk/haplotypecaller/wrapper.py

Added `--bam-output` option to output  assembled haplotypes and locally realigned reads.
More info in:
https://gatk.broadinstitute.org/hc/en-us/articles/360037422451-HaplotypeCaller#--bam-output

Added bam-output option

---

bio/fastqc/test/Snakefile
bio/fastqc/wrapper.py

* Remove quoting on log file, since it would assume it was another input file and actually not log anything
* Removed `quiet` flag, since it can be added in the `params`

Fixed small bug with log file and removed quiet flag

---

bio/gatk/baserecalibrator/test/Snakefile
bio/gatk/baserecalibrator/wrapper.py

The tool allows for multiple --known-sites files as noted in the documentation at https://gatk.broadinstitute.org/hc/en-us/articles/360037593511-BaseRecalibrator

Implemented passing multiple --known-sites to gatk BaseRecalibrator.

---

bio/delly/wrapper.py
bio/picard/markduplicateswithmatecigar/environment.yaml
bio/picard/markduplicateswithmatecigar/meta.yaml
bio/picard/markduplicateswithmatecigar/wrapper.py

Code clean-up to use snakemake's `java_opts` function

Code clean-up on Markduplicateswithmatecigar

---

bio/fastqc/wrapper.py
bio/samtools/bam2fq/interleaved/wrapper.py
bio/samtools/bam2fq/separate/wrapper.py
bio/samtools/calmd/wrapper.py
bio/samtools/depth/wrapper.py
bio/samtools/faidx/wrapper.py
bio/samtools/fixmate/wrapper.py
bio/samtools/flagstat/wrapper.py
bio/samtools/index/wrapper.py
bio/samtools/merge/wrapper.py
bio/samtools/sort/wrapper.py
bio/samtools/view/wrapper.py

Added `log` files to several wrappers.

Add log files to several wrappers

---

docs/index.rst

This documents the solution found by @nikostr and closes #237 .

add example of using GitHub raw URL for wrapper location specification

---

bio/sambamba/flagstat/wrapper.py
bio/sambamba/slice/wrapper.py

Set `stdout=False` for logging.

Updated log for sambamba flagstat and slice

---

.github/pull_request_template.md

* added two entries (link to docs in `meta.yaml` `description:` and automatic command line argument inference)
* some minor wording
* reordered a bit

suggestions for the pull request template

---

bio/bwa/mem/environment.yaml
bio/bwa/mem/meta.yaml
bio/bwa/mem/test/Snakefile
bio/bwa/mem/test/Snakefile_picard
bio/bwa/mem/test/Snakefile_samtools
bio/bwa/mem/wrapper.py
test.py

and removed tmp file specification, since it can be done through `sort_extra`.

Fixed bug when specifying queryname sorting 

---

utils/datavzrd/environment.yaml

Automatic update of {conda_env_path}.

perf: autobump utils/datavzrd/environment.yaml

---

bio/bcftools/call/environment.yaml

Automatic update of bio/bcftools/call/environment.yaml.

perf: autobump bio/bcftools/call/environment.yaml

---

bio/bcftools/index/environment.yaml

Automatic update of bio/bcftools/index/environment.yaml.

perf: autobump bio/bcftools/index/environment.yaml

---

utils/datavzrd/meta.yaml

docs: Update datavzrd url

---

bio/sambamba/index/environment.yaml
bio/sambamba/markdup/environment.yaml

Version 0.8.2 does not have the macOS tarball on bioconda
* wherever possible, command line arguments are inferred and set automatically …

perf: Sambamba version update 0.8.2->1.0

---

bio/gffread/wrapper.py

Addresses bug discussed in detail in #1794. Details about proposed fix implemented in this PR are discussed in that issue report as well.

fix: gffread - properly generate fasta output

---

docs/generate_docs.py

See #1799. Not sure if this is the solution you are looking for..

fix: build docs on fork

---

utils/datavzrd/environment.yaml

perf: Update datavzrd version to 2.35.3

---

utils/datavzrd/environment.yaml

perf: Update datavzrd to 2.36.2

---

docs/index.rst

Add list of maintainers.
@johanneskoester feel free to edit accordingly.
* the `environment.yaml` pinning has been updated by running …

docs: add list of maintainers

---

utils/datavzrd/environment.yaml

perf: Update Datavzrd to 2.36.9

---

utils/datavzrd/environment.yaml

perf: Update Datavzrd to 2.36.12

---

utils/datavzrd/environment.yaml

perf: Update Datavzrd wrapper

---

.readthedocs.yaml

While the contributions guidelines are more extensive, please particularly ensure that:

chore: unshallow readthedocs clone
